name: Destroy EKS Infrastructure

on:
  workflow_dispatch:  # This allows manual triggering

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  TF_STATE_BUCKET: "regtech-iac-logs-2024"

jobs:
  Destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -reconfigure

      - name: Destroy Infrastructure
        working-directory: ./terraform
        run: terraform destroy -auto-approve

      - name: Delete State Bucket
        if: success()
        run: |
          # Empty the bucket first
          aws s3 rm s3://${{ env.TF_STATE_BUCKET }} --recursive
          # Delete the bucket
          aws s3api delete-bucket --bucket ${{ env.TF_STATE_BUCKET }} --region us-east-1